apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-nginx-deployment
  labels:
    component: test-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      component: test-nginx
  template:
    metadata:
      labels:
        component: test-nginx
    spec:
      containers:
      - name: test-nginx
        image: miyazi777/test-nginx
