apiVersion: v1
kind: Service
metadata:
  name: test-nginx-service
spec:
  selector:
    component: test-nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001
  type: NodePort
